
name: matrix job 
on: workflow_dispatch
jobs:
 build:
  strategy: 
   matrix:
    node-version: [ 12,13,14]
    operating-system: [ ubuntu-latest, windows-latest]
    include:
      - node-version: 18
        operating-system: ubuntu-latest
    exclude: 
      - node-version: 12
        operating-system: windows-latest
  runs-on: ${{matrix.operating-system}}
  steps: 
   - name: get code
     uses: actions/checkout@v3
   - name: install nodejs
     uses: actions/setup-node@v3
     with: 
      node-version: ${{matrix.node-version}}
  #  - name: install dependciners
  #    run: npm ci 
  #  - name: build project
  #    run: npm run build 
     